[db]
hostname = localhost
dbusername = pihomedbadmin
dbpassword = pihome2018
dbname = pihome
connect_error = Sorry We are Experiencing MySQL Database Connection Problem...

version = 1.77
build = 180321
